
version: '3.9'

services:
  database: 
    container_name: event_ms_db
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: event_service_db
    volumes:
      - event_ms_db:/var/lib/postgresql/data
    networks:
      - keycloak-net
  keycloak_db_service: 
    container_name: keycloak_db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak_db
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db_service:5432/keycloak_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db_service
    networks:
      - keycloak-net

volumes:
  keycloak-db-data:
  event_ms_db:

networks:
  keycloak-net:
