server:
  port: 8765

spring:
  application:
    name: eventify-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/events/**
              filters: []

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/eventify-realm

eureka:
  client:
    service-url:
      defaultZone: http://name-server:8761/eureka 


