server:
    port: 8888
spring:
    application:
        name: eventify-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/RodrigoPLopesIA/eventify-microservices
                    search-paths: 
                        - user-service*
                        
          
