server:
    port: 8888
spring:
    application:
        name: eventify-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/RodrigoPLopesIA/eventify-config-server-envs
                    search-paths:
                        - .
                    clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
