spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "optional:configserver:http://localhost:8888/"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/eventify-realm

  profiles:
    active:
    - dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
  