spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:http://localhost:8888/"
  
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false