spring:
  application:
    name: event-service
  config:
    import: "optional:configserver:http://localhost:8888/"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/eventify-realm

  profiles:
    active:
    - dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
  