name: Deploy microservices

on:
    push: 
        branches: ["main"]
    pull_request: 
        branches: ["main"]
jobs:
    
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4


            - name: "Login to docker hub"
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}  
                password: ${{secrets.DOCKER_ACCESS_SECRET}}

            - name: "Setup Java 21"
              uses: actions/setup-java@v4
              with:
                distribution: "adopt"
                java-version: "21"
