name: Deploy microservices

on:
    push: 
        branches: ["main"]
    pull_request: 
        branches: ["main"]
jobs:
    
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "Setup Java 21"
              uses: actions/setup-java@v4
              with:
                distribution: "adopt"
                java-version: "21"


            - name: "Build Project"
              working-directory: ./eventify-name-server
              run: mvn clean package -DskipTests

            - name: "Login to docker hub"
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}  
                password: ${{secrets.DOCKER_ACCESS_SECRET}}

            - name: "Create Docker build"
              working-directory: ./eventify-name-server
              run: docker build -t rodrigolopes2022/eventify-registry-server-eureka .

            - name: "Push image"
              working-directory: ./eventify-name-server
              run: docker push rodrigolopes2022/eventify-registry-server-eureka:latest
            
            
